name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2

      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Download Modules
        run: go mod download

      - name: Run Tests
        run: go test ./... -count=1 --cover -v

      - name: Build
        run: go build -ldflags="-s -w" -o ./cf-shared-apigwv2 .

